apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  POSTGRES_DB: {{ .Values.postgresDb | b64enc }}
  POSTGRES_USER: {{ .Values.postgresUser | b64enc }}
  POSTGRES_PASSWORD: {{ .Values.postgresPassword | b64enc }}
---
